const CarNames = [
    {
    id:'1',
    name:'Audi',
},
    {
    id:'2',
    name:'BMW',
},
    {
    id:'3',
    name:'Mercedes',
},
]
const CarPrices = [
    {
    id:'1',
    amount:'$1000',
},
    {
    id:'2',
    amount:'$2000',
},
    {
    id:'3',
    amount:'$3000',
},
]
const categories = [
    {
        id:1,
        name:`suv`,
        icon:`./icon_van.svg`
    },
    {
        id:2,
        name:'Sedan',
        icon:`./icon_suv.svg`
    },
    {
        id:3,
        name:'Hatchback',
        icon:`./icon_truck.svg`
    },
    {
        id:4,
        name:'Couple',
        icon:`./icon_couple_car.svg`
    },
    {
        id:5,
        name:'Hybrid',
        icon:`./icon_suv.svg`
    },
    {
        id:6,
        name:'Convertable',
        icon:`./icon_couple_car.svg`
    },
    {
        id:7,
        name:'Truck',
        icon:`./icon_truck.svg`
    },
    {
        id:8,
        name:'Van',
        icon:`./icon_van.svg`
    },
    {
        id:9,
        name:'Electric car',
        icon:`icon_electric_car.svg`
    },
]

export default{CarNames, CarPrices, categories}